apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "cf-operator.fullname" . }}
spec:
  replicas: 1
  selector:
    matchLabels:
      name: cf-operator
  template:
    metadata:
      labels:
        name: cf-operator
    spec:
      serviceAccountName: {{ template "cf-operator.serviceAccountName" . }}
      containers:
        - name: cf-operator
          image: "{{ .Values.image.org }}/{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
          - containerPort: 60000
            name: metrics
          command:
          - cf-operator
          imagePullPolicy: {{ .Values.image.pullPolicy | quote }}
          env:
            - name: CF_OPERATOR_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "cf-operator"
            - name: DOCKER_IMAGE_ORG
              value: "{{ .Values.image.org }}"
            - name: DOCKER_IMAGE_REPOSITORY
              value: "{{ .Values.image.repository }}"
            - name: DOCKER_IMAGE_TAG
              value: "{{ .Values.image.tag }}"
          readinessProbe:
            httpGet:
              path: /readyz
              port: 8080
              scheme: "HTTP"
            initialDelaySeconds: 2