apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: quarkssecrets.quarks.cloudfoundry.org
  annotations:
    "helm.sh/hook": crd-install
spec:
  conversion:
    strategy: None
  group: quarks.cloudfoundry.org
  names:
    kind: QuarksSecret
    listKind: QuarksSecretList
    plural: quarkssecrets
    shortNames:
    - qsec
    - qsecs
    singular: quarkssecret
  preserveUnknownFields: false
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        spec:
          properties:
            request:
              properties:
                certificate:
                  properties:
                    CAKeyRef:
                      properties:
                        key:
                          type: string
                        name:
                          type: string
                      type: object
                    CARef:
                      properties:
                        key:
                          type: string
                        name:
                          type: string
                      type: object
                    activateEKSWorkaroundForSAN:
                      type: boolean
                    alternativeNames:
                      items:
                        type: string
                      nullable: true
                      type: array
                    commonName:
                      type: string
                    isCA:
                      type: boolean
                    serviceRef:
                      items:
                        type: object
                        x-kubernetes-preserve-unknown-fields: true
                      nullable: true
                      type: array
                    signerType:
                      type: string
                    usages:
                      items:
                        type: object
                        x-kubernetes-preserve-unknown-fields: true
                      nullable: true
                      type: array
                  type: object
              type: object
            secretName:
              description: The name of the generated secret
              minLength: 1
              type: string
            type:
              description: 'What kind of secret to generate: password, certificate,
                ssh, rsa'
              minLength: 1
              type: string
          required:
          - request
          - secretName
          - type
          type: object
        status:
          properties:
            generated:
              type: boolean
            lastReconcile:
              type: object
          type: object
      type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
